name: Render and Deploy

on:
  push:
    branches: [main]  # or "master" or whichever branch you use

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install Quarto (if needed)
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: latest

      - name: Install dependencies
        run: |
          Rscript -e 'install.packages(c("rmarkdown", "quarto"))'

      - name: Render document
        run: |
          if [ -f "*.qmd" ]; then
            quarto render
          elif [ -f "*.Rmd" ]; then
            Rscript -e 'rmarkdown::render(list.files(pattern = "\\.Rmd$")[1])'
          fi

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./  # adjust if HTML goes into a subfolder
