name: Render and Deploy

on:
  push:
    branches: [master]  # or "master" or whichever branch you use
    
permissions:
    contents: write
    pages: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install Quarto (if needed)
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Install dependencies
        run: |
          Rscript -e 'install.packages(c("quarto"))'

      - name: Create _site directory
        run: mkdir -p _site

      - name: Render .qmd files using Quarto CLI
        run: |
          for file in $(find . -name "*.qmd"); do
            quarto render "$file" --output-dir "_site"
          done

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
          publish_branch: gh-pages
